FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python scripts/initialize_database.py
EXPOSE 8080
CMD ["python","main.py","--no-dashboard"]
